# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      # - id: check-json
      # 
      # NOTE: The standar 'check-json' doesn't support JSON
      # with comments.  More info: 
      #   https://github.com/pre-commit/pre-commit-hooks/issues/395
      #
      # - repo: https://gitlab.com/bmares/check-json5
      #   rev: v1.0.0
      #   hooks:
      #   - id: check-json5
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      - id: ruff
